server:
  port: 8080

spring:
  application:
    name: student-management-api
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017}
      database: ${MONGODB_DATABASE:student_management}

app:
  jwt:
    secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970} # 256-bit secret key in hex
    expiration-ms: ${JWT_EXPIRE:86400000} # 24 hours in ms
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:*,http://127.0.0.1:*,https://*.onrender.com}

logging:
  level:
    root: INFO
    com.studentmanagement.studentapi: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
  file:
    name: logs/application.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
